"""init

Revision ID: 7bb90ad93a3a
Revises: 
Create Date: 2024-11-12 17:35:53.905734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb90ad93a3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('open', sa.Double(), nullable=True),
    sa.Column('high', sa.Double(), nullable=True),
    sa.Column('low', sa.Double(), nullable=True),
    sa.Column('close', sa.Double(), nullable=True),
    sa.Column('volume', sa.Double(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('time_open', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_close', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kline_id_symbol'), 'kline', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_kline_time_open'), 'kline', ['time_open'], unique=False)
    op.create_table('order_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('ask', sa.Text(), nullable=True),
    sa.Column('bid', sa.Text(), nullable=True),
    sa.Column('time_open', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_book_id_symbol'), 'order_book', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_order_book_time_open'), 'order_book', ['time_open'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_book_time_open'), table_name='order_book')
    op.drop_index(op.f('ix_order_book_id_symbol'), table_name='order_book')
    op.drop_table('order_book')
    op.drop_index(op.f('ix_kline_time_open'), table_name='kline')
    op.drop_index(op.f('ix_kline_id_symbol'), table_name='kline')
    op.drop_table('kline')
    op.drop_table('symbol')
    # ### end Alembic commands ###
